apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-pihole-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-dnsmasq-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  labels:
    app: pihole-dns
spec:
  ports:
  - port: 53
    name: "dns"
    protocol: UDP
  - port: 67
    protocol: UDP
    name: "dns2"
  type: LoadBalancer
  selector:
    app: pihole
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-http
  labels:
    app: pihole-http
spec:
  ports:
  - port: 80
    name: "http"
    protocol: TCP
  - port: 443
    protocol: TCP
    name: "https"
  selector:
    app: pihole
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pihole-ingress
spec:
  rules:
  - host: dns.homer.fi
    http:
      paths:
      - path: /admin
        backend:
          serviceName: pihole-http
          servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-deployment
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole 
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:v5.5.1-armhf-stretch
        volumeMounts:
        - name: etc-pihole
          mountPath: /etc/pihole
        - name: etc-dnsmasq
          mountPath: /etc/dnsmasq.d
        - name: wildcard-conf
          mountPath: /etc/dnsmasq.d/wildcard.conf
          subPath: wildcard.conf
        ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
          protocol: TCP
        - containerPort: 67
          protocol: UDP
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        env:
        - name: TZ
          value: "Europe/Helsinki"
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole-webpasswd
              key: webpasswd
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 127.0.0.1
        - 1.1.1.1
      volumes:
      - name: wildcard-conf
        configMap:
          name: pihole-wildcard-config
          items:
          - key: wildcard.conf
            path: wildcard.conf
      - name: etc-pihole
        persistentVolumeClaim:
          claimName: etc-pihole-pvc
      - name: etc-dnsmasq
        persistentVolumeClaim:
          claimName: etc-dnsmasq-pvc
