---
- name: Install os dependencies
  yum:
    name:
      - openssl
    state: present 
- name: Copy generate_cert.sh
  copy:
    src: ../files/generate_cert.sh
    dest: /opt/k8s/generate_cert.sh
    mode: 700
- name:
  file:
    path: /opt/k8s/.ssl
    state: directory
- name: Generate certificates
  shell: /opt/k8s/generate_cert.sh
  args: 
    creates: /opt/k8s/.ssl/cert.pem
  notify: restart k3s
- name: Copy & auto-deploy registry.yaml
  copy:
    src: ../files/registry.yaml
    dest: /var/lib/rancher/k3s/server/manifests/registry.yaml
